---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=embedded-jdg-openshift&var-version=0.0.1-SNAPSHOT
  labels:
    provider: fabric8
    project: embedded-jdg-openshift
    version: 0.0.1-SNAPSHOT
    group: org.everythingjboss.jdg
  name: embedded-jdg-openshift
spec:
  replicas: 1
  selector:
    project: embedded-jdg-openshift
    provider: fabric8
    group: org.everythingjboss.jdg
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=embedded-jdg-openshift&var-version=0.0.1-SNAPSHOT
      labels:
        provider: fabric8
        project: embedded-jdg-openshift
        version: 0.0.1-SNAPSHOT
        group: org.everythingjboss.jdg
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_DIR
          value: /deployments
        - name: JAVA_OPTIONS
          value: -Djava.net.preferIPv4Stack=true   
        image: embedded-jdg-openshift:latest
        resources:
          limits:
            memory: "600Mi"
          requests:
            memory: "235Mi"
        imagePullPolicy: IfNotPresent
        name: java-exec
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: kube
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - java-exec
      from:
        kind: ImageStreamTag
        name: embedded-jdg-openshift:latest
    type: ImageChange
