---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    provider: fabric8
    project: embedded-jdg-openshift
    version: 0.0.1-SNAPSHOT
    group: org.everythingjboss.jdg
  name: embedded-jdg-openshift
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: embedded-jdg-openshift
    provider: fabric8
    group: org.everythingjboss.jdg
